### ISSUE TITLE
Add "Select All" button

### ISSUE THREAD

**Issue by guytepper** [guytepper/lastfm-unscrobbler#1]
Add a button that will allow selecting all checkboxes in the current page.  

**Some behaviour caveats:**
- On the profile page, only the recent tracks should be selected (instead of all tracks on the page).
- When pressing the button again, all tracks should be deselected.

**How to approach:**

1. Create a new button element and insert it to the page. You can see an example [here](https://github.com/guytepper/lastfm-unscrobbler/blob/master/unscrobbler.js#L26-L30).
2. You'll probably need to adjust some of the styles Last.fm uses in order to make it positioned correctly. 
3. Attach an onclick event listener, that when fires runs through all the checkboxes and checks them (and then change it so the button will deselect them).

All of that should take place in the `unscrobbler.js` file.

**Styling & Position:**
For styling, let's use the `btn-secondary` and `btn-sm` classes that Last.fm use to style small buttons.  
It looks like that:
![screen shot 2018-10-02 at 11 13 12](https://user-images.githubusercontent.com/13344923/46336676-2f5ca580-c634-11e8-9564-25c1dd6936ab.png)

The button should be placed on top of the page:
![image](https://user-images.githubusercontent.com/13344923/45059474-d1748680-b0a4-11e8-9d43-8dfa2be7a860.png)

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by guytepper** [comment]
@hiteshpr Awesome! Thank you so much! I've updated the issue with more instructions. 

If you have questions or need any help feel free to ask! :-)

**Comment by guytepper** [comment]
@hiteshpr are you still interested in working on this? If not, I'll take it :)
