### ISSUE TITLE
Publish Addon on Firefox

### ISSUE THREAD

**Issue by CennoxX** [guytepper/lastfm-unscrobbler#10]
Firefox also supports WebExtensions, big adjustments shouldn't be necessary.

**Comment by guytepper** [comment]
Thanks for the suggestion! I'll try to port it in the upcoming days :-)

**Comment by guytepper** [comment]
The add-on has been submitted for review, I'll let you know once it's approved. 🙂

**Comment by CennoxX** [comment]
It's available here: https://addons.mozilla.org/en-US/firefox/addon/last-fm-unscrobbler/ 🎉
