### ISSUE TITLE
Show Progress indicator?

### ISSUE THREAD

**Issue by jeremymeyers** [guytepper/lastfm-unscrobbler#11]
Is there possibly a way to show the deletion progress with a in-window pop-up rather than having no visual cue that the scrobbles are being deleted?

**Comment by guytepper** [comment]
Do you find it needed? Usually the scrobbles are deleted and greyed out within 1-2 seconds.

**Comment by CennoxX** [comment]
Seems like an UI problem on last.fm's side. Even if you delete a single scrobble without the addon, the transparency makes it look like the deletion is still in progress...

**Comment by guytepper** [comment]
Yup. The extension matches the normal deletion behavior of the website. 

Closing this for now :)
