### ISSUE TITLE
not currently working?

### ISSUE THREAD

**Issue by aeleeds** [guytepper/lastfm-unscrobbler#22]
Hi! Is this currently working? I'm running Chrome Version 92.0.4515.159 on MacOS Mojave. The extension activates, the checkboxes and menu item appear, but nothing happens when I click on delete. In the javascript console I see:

```
unscrobbler.js:150 Uncaught TypeError: Cannot read property 'click' of null
    at unscrobbler.js:150
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.deleteScrobbles (unscrobbler.js:147)
```

What else? Anything I can do to troubleshoot?

**Comment by guytepper** [comment]
Working for me, have you tried the following?

>* Ensure you are logged in to your Last.FM account
>* Ensure you clicked the extension icon while being in your profile / scrobble library pages - the extension doesn't work on artist pages / albums.
>* Try to refresh the page and wait 2 seconds after the page loads before clicking the extension icon.

**Comment by aeleeds** [comment]
Apologies— it turns out that I wasn't logged into the last.fm web account when I was doing it, but thought I was. Works fine. Thanks for making this.

**Comment by guytepper** [comment]
Glad to hear! Happy unscrobbling :-)
