### ISSUE TITLE
Firefox and Chrome different scrobble select behavior

### ISSUE THREAD

**Issue by flickur** [guytepper/lastfm-unscrobbler#23]
On Chrome you can click anywhere within the scrobble (the area marked on red) to check the small tickbox, but on Firefox you have to click directly on the very small box to select the song. This makes selecting multiple scrobbles very tedious compared to the Chrome behaviour. Is it possible to implement this on Firefox the same way it works on Chrome?

![image](https://user-images.githubusercontent.com/40724723/135272764-1c4bf230-b837-4c94-8ec9-8cf43669b2f3.png)

**Comment by guytepper** [comment]
Hey! Thank for the report.
Lazy me didn't update the Firefox version to match the chrome one. I've submitted the latest version now - I'll let you know once they approve it!

**Comment by guytepper** [comment]
Released
