### ISSUE TITLE
Extension doesn't work correctly in Firefox

### ISSUE THREAD

**Issue by ethanrw** [guytepper/lastfm-unscrobbler#24]
The extension only works when you click the extension icon - however this doesn't appear in Firefox.

The icon doesn't appear in the toolbar by default and also can't be added via the Customize Toolbar menu - it seems as if the extension has no toolbar icon/behaviour.

I'm using Firefox 101.0 on Windows and Mac and the same issue occurs on both.

Not the biggest deal as I can swap back to Chrome when needed but some users could be confused :)

**Comment by CennoxX** [comment]
In Firefox, the button is located in the address bar - in the upper right corner of the image below:
![grafik](https://user-images.githubusercontent.com/6975881/172391276-a022eef6-0248-4c28-a288-c6821425c3ff.png)

**Comment by guytepper** [comment]
Hey, the Firefox extension behaves different - it shows the extension icon on the address bar instead on the toolbar, and only when you're on Last.FM. 

![image](https://user-images.githubusercontent.com/13344923/172449014-132239d5-bea1-4502-a20e-4920261b5b7c.png)

Does it show up for you there?
