### ISSUE TITLE
Error message when using the extension on Google Chrome

### ISSUE THREAD

**Issue by louxcx** [guytepper/lastfm-unscrobbler#25]
An error message like this pops up whenever the extension is clicked on, even while on the mentioned pages. Didn't happen a few days ago, so it seems to be new. Sometimes it works without any error, but that's typically only on the first page of the user scrobbles library
![ERROR](https://user-images.githubusercontent.com/108607414/177030721-d7044f7a-0f39-4a79-adf5-f79f367616de.jpeg)

**Comment by guytepper** [comment]
Thanks for the report!
I've fixed the issue and submitted a new version. 
It should be available in 1-2 days - let me know if the error still exists :)
