### ISSUE TITLE
Support "Library > Tracks" scrobbles page

### ISSUE THREAD

**Issue by sorarideblog** [guytepper/lastfm-unscrobbler#26]
![image](https://user-images.githubusercontent.com/54093651/178503867-61d987a5-648b-47fc-b211-4125a800168f.png)

I think it's nice to support user library tracks scrobbles page of URL like `https://www.last.fm/user/{USER}/library/music/{ARTIST}/_/{TRACK}?date_preset=ALL`.

**Comment by CennoxX** [comment]
There is no delete option in the context menu of the Tracks site, this addon works internally by clicking the delete scrobble entry, so adding any sites isn't that easy at all.
Tracks site, without delete scrobbles:
![grafik](https://user-images.githubusercontent.com/6975881/178668192-a9625e87-5da7-4e2f-a383-17863433c9ff.png)
compare that to Scrobbles:
![grafik](https://user-images.githubusercontent.com/6975881/178668117-b7c593f0-e11a-463f-9d39-50d39eb07b9c.png)

**Comment by guytepper** [comment]
@CennoxX as far as I understood @sorarideblog talks about the track scrobble history section; for example a click on a track scrobble amount:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/13344923/178912515-5b5d2e30-e9f8-4d7e-817b-7faf70b14e00.png">

takes you to a page underneath the tracks tab with an option to delete the scrobbles.
<img width="593" alt="Screen Shot 2022-07-14 at 9 12 54" src="https://user-images.githubusercontent.com/13344923/178912768-8673e353-6ece-47a6-9e96-f9992f125ef0.png">

I'll try to whitelist the pages later on, or if @CennoxX you'd like to take it over, it'd be much appreciated! 😊

**Comment by sorarideblog** [comment]
Oh, I was just about to reply to @CennoxX just like that. 
That's what I wanted to say.

I don't understand what the whitelist is, but if I don't need to work on this issue myself, I'll be looking forward to it.

Thanks,
