### ISSUE TITLE
I didn't see the icon for activating the checkboxes

### ISSUE THREAD

**Issue by Iveldie** [guytepper/lastfm-unscrobbler#30]
I use firefox and i dont see the icon and i cant use. Where is the icon? how can i activate it?

**Comment by guytepper** [comment]
Hey! the icon should appear in the address bar on the right side when you're visiting your profile.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/13344923/211188943-8da7ca38-a66d-4451-a661-548038a40825.png">

(I notice now the icon is dimmed.. will have to check why it's happening)
