### ISSUE TITLE
Suggestion: modify this to work in library's track page

### ISSUE THREAD

**Issue by flickur** [guytepper/lastfm-unscrobbler#31]
Hey, 

so I noticed this doesn't work on the track page within library, even though it's possible to delete the scrobbles there per track. So this page: last.fm/user/username/library/music/artist/_/track.

Would it be possible to get the unscrobbler to work there as well?

**Comment by guytepper** [comment]
Hey, thanks for the suggestion. I believe it's possible. I'll check it later this week :)

**Comment by guytepper** [comment]
I forgot that it's already in, added via #27.

Are you using Firefox? I see that the error shows up in Firefox but not in Chrome, so I might've messed up with the release build of Firefox.

**Comment by flickur** [comment]
> I forgot that it's already in, added via #27.
> 
> Are you using Firefox? I see that the error shows up in Firefox but not in Chrome, so I might've messed up with the release build of Firefox.

Yeah i'm using the latest version of firefox.

**Comment by guytepper** [comment]
I've submitted a fix for Firefox, should be available publicly soon. 
Let me know if the issue still occurs. Thanks for reporting the issue! 🙏
