### ISSUE TITLE
Can't set extension to auto-enable on Chrome settings

### ISSUE THREAD

**Issue by guttitto** [guytepper/lastfm-unscrobbler#32]
I can enable or disable "Allow this extension to read and change all your data on websites you visit", but it doesn't change anything, in both cases the only option is to activate the extension by clicking it, it doesn't let me set it to be activated only on Last.fm automatically or on all sites. I tried both downloading the extension from Chrome Web Store and running it by downloading the source code, the same thing happens in both scenarios.
![image](https://user-images.githubusercontent.com/25709670/223827379-5b350ef0-970b-4ac3-bb1f-b42a68ade329.png)
![image](https://user-images.githubusercontent.com/25709670/223827738-316fa681-6c48-4f00-bbc9-e697560031b0.png)

**Comment by guytepper** [comment]
This is how the extension works - by clicking on the extension icon, so the normal layout of the site will be preserved :)
The "automatic" option of chrome means you won't be asked to let the extension access the website each time.

It would be nice to have the option to let the user decide to have the extension always run. Sadly, I don't have time to implement this at the moment.
