### ISSUE TITLE
Doesn't works on Chrome and Firefox

### ISSUE THREAD

**Issue by blablabla1234567890123** [guytepper/lastfm-unscrobbler#33]
Hi, 
I tried today to use the extension on Chrome and it doesn't works anymore ? I don't have any tickboxes even when I click on the extension, nothing happens.

And on Firefox, it says the extension can't read nor modify the data (the message is in french because I'm french so I tried to translate it in English) and the extension is grey, can't use it. Thanks

**Comment by guytepper** [comment]
Hey! It works fine for me both for on Firefox & Chrome. Did you try running the extension on a valid page (your profile / library)?

**Comment by icarofr** [comment]
Can confirm that it doesn't work on Firefox (extension is grayed out). Seems to work on Chrome though

**Comment by guytepper** [comment]
@icarofr can you please provide the URL you're trying to run the extension on?

**Comment by icarofr** [comment]
@guytepper I've tried on both 
- https://www.last.fm/user/HigherCoward
and 
- https://www.last.fm/user/HigherCoward/library

None of these seem to work on Firefox.

**Comment by guytepper** [comment]
@icarofr I can't reproduce, the extension works for me 🫤
- when you click the extension icon while on your profile page, do you get an alert or nothing happens?
- can you also provide the firefox version & extension version you are running?
- after that - can you try to delete the extension and reinstall and report if anything changes?

**Comment by icarofr** [comment]
Weird. I'm using Firefox 117.0, and the extension version is 1.6.2. The extension is completely grayed out when I go to one of these two URLs.


![example](https://github.com/guytepper/lastfm-unscrobbler/assets/47608323/4e0ea38a-ed35-442a-85da-748ca8c00e53)

**Comment by CennoxX** [comment]
> Weird. I'm using Firefox 117.0, and the extension version is 1.6.2. The extension is completely grayed out when I go to one of these two URLs.

@icarofr You have to click on the icon in your URL-bar. 
Maybe this should be noted somewhere in the description of the addon, or a click on the Addon in the extension menu should do the same as a click on the URL-icon.

**Comment by icarofr** [comment]
Oh. Yep, that part wasn't obvious, but ideally a click in the addon should trigger the action too.

Anyway, thank you. It does seem to work properly and I don't need to fire Chrome when I accidentally fall asleep playing a track on loop 😅

**Comment by guytepper** [comment]
Thanks @CennoxX for catching that.

For now I've edited the Firefox extension page with more detailed instructions and a new screenshot. Hopefully this will be sufficient :)
