### ISSUE TITLE
CSS puts checkbox too close to 'heart' button in chrome/mac

### ISSUE THREAD

**Issue by jeremymeyers** [guytepper/lastfm-unscrobbler#6]
its impossible to click an individual track checkbox on chrome/mac because the heart is on top of it. (happy to provide more configuration details)
![Screenshot 2019-05-29 14 18 32](https://user-images.githubusercontent.com/3514095/58581123-c8bc7580-821c-11e9-88fd-851232d84027.png)

**Comment by guytepper** [comment]
Thanks for the report! 🙂
It looks like you have the new library design, which I haven't got yet. I'll try to ask Last.fm to grant me access to it.

**Comment by jeremymeyers** [comment]
ok! I'm happy to do some beta testing if you'd like, too.

**Comment by guytepper** [comment]
Hi @jeremymeyers! I've just pushed an update to the Chrome web store that makes the extension compatible with the new design. 
Let me know if you see something wrong, and once again - thanks for reporting 😊
